@BASE_URL={{$dotenv BACKEND_BASE_URL}}
@KEY=luecke1
@SHEET=index.html
@USER=dummywert
@VALUE=Testantwort

### Antwort anlegen/aktualisieren
POST {{BASE_URL}}answer
Content-Type: application/json

{
  "key": "{{KEY}}",
  "sheet": "{{SHEET}}",
  "user": "{{USER}}",
  "value": "{{VALUE}}"
}

### Alle Antworten (ohne Filter)
GET {{BASE_URL}}answer

### Antworten nach Sheet (Pfad)
GET {{BASE_URL}}answer//{{SHEET}}

### Antworten nach Sheet und User (Pfad)
GET {{BASE_URL}}answer//{{SHEET}}/{{USER}}

### Antworten nach Sheet/User (Query)
GET {{BASE_URL}}answer?sheet={{SHEET}}&user={{USER}}
